Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,9 +2,9 @@ name: Deploy
 
 # Controls when the action will run. 
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
+  # Triggers the workflow on push or pull request events but only for the main branch
   push:
-    branches: [ main ]
+    branches: [main]
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -14,18 +14,32 @@ jobs:
     runs-on: ubuntu-latest
 
     # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:       
-    - name: Deploy using ssh
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.HOST }}
-        username: ${{ secrets.USERNAME }}
-        key: ${{ secrets.SSH_PRIVATE_KEY }}
-        port: 22
-        script: |
-          cd /home/nhatminh3004/github_action_docker_spring_mysql/
-          git pull origin main
-          sudo docker-compose down
-          sudo docker-compose up --build
-          echo Build sucess
-          exit 0
+    steps:
+      - name: Deploy using ssh
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            cd /home/nhatminh3004/github_action_docker_spring_mysql/
+            git pull origin main
+            sudo docker-compose down
+            sudo docker-compose up --build
+            echo Build success
+            
+            # Wait for the application to start (you can adjust the waiting time as needed)
+            sleep 30
+            
+            # Check if the application is accessible on port 8080
+            response=$(curl -s -o /dev/null -w "%{http_code}" http://http://20.163.217.108/test)
+            
+            # Check if the response code is 200 (OK)
+            if [ $response -eq 200 ]; then
+              echo "Spring Boot application is running successfully."
+              exit 0  # Success
+            else
+              echo "Spring Boot application failed to start or is not accessible on port 8080."
+              exit 1  # Failure
+            fi
